"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class geolocation_t(object):
    __slots__ = ["lat", "lon", "alt"]

    def __init__(self):
        self.lat = 0.0
        self.lon = 0.0
        self.alt = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(geolocation_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.lat, self.lon, self.alt))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != geolocation_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return geolocation_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = geolocation_t()
        self.lat, self.lon, self.alt = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if geolocation_t in parents: return 0
        tmphash = (0x5cdb7d92f9648302) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if geolocation_t._packed_fingerprint is None:
            geolocation_t._packed_fingerprint = struct.pack(">Q", geolocation_t._get_hash_recursive([]))
        return geolocation_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

