"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import messages.geolocation_t

class georef_ret_t(object):
    __slots__ = ["command_id", "result", "pixel_loc"]

    def __init__(self):
        self.command_id = 0
        self.result = 0
        self.pixel_loc = messages.geolocation_t()

    def encode(self):
        buf = BytesIO()
        buf.write(georef_ret_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qB", self.command_id, self.result))
        assert self.pixel_loc._get_packed_fingerprint() == messages.geolocation_t._get_packed_fingerprint()
        self.pixel_loc._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != georef_ret_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return georef_ret_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = georef_ret_t()
        self.command_id, self.result = struct.unpack(">qB", buf.read(9))
        self.pixel_loc = messages.geolocation_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if georef_ret_t in parents: return 0
        newparents = parents + [georef_ret_t]
        tmphash = (0xcb5b02d2820b3df5+ messages.geolocation_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if georef_ret_t._packed_fingerprint is None:
            georef_ret_t._packed_fingerprint = struct.pack(">Q", georef_ret_t._get_hash_recursive([]))
        return georef_ret_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

