"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class jellyfish_t(object):
    __slots__ = ["jellyfish_id", "num_pixels", "center", "bounding"]

    def __init__(self):
        self.jellyfish_id = 0
        self.num_pixels = 0
        self.center = [ 0 for dim0 in range(2) ]
        self.bounding = [ 0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(jellyfish_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.jellyfish_id, self.num_pixels))
        buf.write(struct.pack('>2i', *self.center[:2]))
        buf.write(struct.pack('>4i', *self.bounding[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != jellyfish_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return jellyfish_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = jellyfish_t()
        self.jellyfish_id, self.num_pixels = struct.unpack(">ii", buf.read(8))
        self.center = struct.unpack('>2i', buf.read(8))
        self.bounding = struct.unpack('>4i', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if jellyfish_t in parents: return 0
        tmphash = (0xfdb81b66546f3125) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if jellyfish_t._packed_fingerprint is None:
            jellyfish_t._packed_fingerprint = struct.pack(">Q", jellyfish_t._get_hash_recursive([]))
        return jellyfish_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

