"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class payload_cmd_t(object):
    __slots__ = ["command_id", "camera_name", "operation"]

    def __init__(self):
        self.command_id = 0
        self.camera_name = ""
        self.operation = ""

    def encode(self):
        buf = BytesIO()
        buf.write(payload_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.command_id))
        __camera_name_encoded = self.camera_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__camera_name_encoded)+1))
        buf.write(__camera_name_encoded)
        buf.write(b"\0")
        __operation_encoded = self.operation.encode('utf-8')
        buf.write(struct.pack('>I', len(__operation_encoded)+1))
        buf.write(__operation_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != payload_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return payload_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = payload_cmd_t()
        self.command_id = struct.unpack(">q", buf.read(8))[0]
        __camera_name_len = struct.unpack('>I', buf.read(4))[0]
        self.camera_name = buf.read(__camera_name_len)[:-1].decode('utf-8', 'replace')
        __operation_len = struct.unpack('>I', buf.read(4))[0]
        self.operation = buf.read(__operation_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if payload_cmd_t in parents: return 0
        tmphash = (0xc4d292d26412eb15) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if payload_cmd_t._packed_fingerprint is None:
            payload_cmd_t._packed_fingerprint = struct.pack(">Q", payload_cmd_t._get_hash_recursive([]))
        return payload_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

