"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class position_t(object):
    __slots__ = ["latitude", "longitude", "altitude"]

    def __init__(self):
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(position_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.latitude, self.longitude, self.altitude))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != position_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return position_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = position_t()
        self.latitude, self.longitude, self.altitude = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if position_t in parents: return 0
        tmphash = (0x7be9f438099fa653) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if position_t._packed_fingerprint is None:
            position_t._packed_fingerprint = struct.pack(">Q", position_t._get_hash_recursive([]))
        return position_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

