"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class quality_ret_t(object):
    __slots__ = ["command_id", "result", "entropy", "blur"]

    def __init__(self):
        self.command_id = 0
        self.result = 0
        self.entropy = 0.0
        self.blur = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(quality_ret_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qBff", self.command_id, self.result, self.entropy, self.blur))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != quality_ret_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return quality_ret_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = quality_ret_t()
        self.command_id, self.result, self.entropy, self.blur = struct.unpack(">qBff", buf.read(17))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if quality_ret_t in parents: return 0
        tmphash = (0xa81b67dea409a043) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if quality_ret_t._packed_fingerprint is None:
            quality_ret_t._packed_fingerprint = struct.pack(">Q", quality_ret_t._get_hash_recursive([]))
        return quality_ret_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

