"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import messages.position_t

class telemetry_t(object):
    __slots__ = ["ACid", "heading", "dest", "dest_time", "tas", "p"]

    def __init__(self):
        self.ACid = ""
        self.heading = 0.0
        self.dest = ""
        self.dest_time = ""
        self.tas = 0.0
        self.p = messages.position_t()

    def encode(self):
        buf = BytesIO()
        buf.write(telemetry_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __ACid_encoded = self.ACid.encode('utf-8')
        buf.write(struct.pack('>I', len(__ACid_encoded)+1))
        buf.write(__ACid_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">f", self.heading))
        __dest_encoded = self.dest.encode('utf-8')
        buf.write(struct.pack('>I', len(__dest_encoded)+1))
        buf.write(__dest_encoded)
        buf.write(b"\0")
        __dest_time_encoded = self.dest_time.encode('utf-8')
        buf.write(struct.pack('>I', len(__dest_time_encoded)+1))
        buf.write(__dest_time_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">f", self.tas))
        assert self.p._get_packed_fingerprint() == messages.position_t._get_packed_fingerprint()
        self.p._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != telemetry_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return telemetry_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = telemetry_t()
        __ACid_len = struct.unpack('>I', buf.read(4))[0]
        self.ACid = buf.read(__ACid_len)[:-1].decode('utf-8', 'replace')
        self.heading = struct.unpack(">f", buf.read(4))[0]
        __dest_len = struct.unpack('>I', buf.read(4))[0]
        self.dest = buf.read(__dest_len)[:-1].decode('utf-8', 'replace')
        __dest_time_len = struct.unpack('>I', buf.read(4))[0]
        self.dest_time = buf.read(__dest_time_len)[:-1].decode('utf-8', 'replace')
        self.tas = struct.unpack(">f", buf.read(4))[0]
        self.p = messages.position_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if telemetry_t in parents: return 0
        newparents = parents + [telemetry_t]
        tmphash = (0xba087b9e3352d626+ messages.position_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if telemetry_t._packed_fingerprint is None:
            telemetry_t._packed_fingerprint = struct.pack(">Q", telemetry_t._get_hash_recursive([]))
        return telemetry_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

